// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: OffHeapCacheProtoBuf.proto

package com.bigfast.protobuf;

public final class OffHeapCacheProtoBuf {
  private OffHeapCacheProtoBuf() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class Operation extends
      com.google.protobuf.GeneratedMessage {
    // Use Operation.newBuilder() to construct.
    private Operation() {
      initFields();
    }
    private Operation(boolean noInit) {}
    
    private static final Operation defaultInstance;
    public static Operation getDefaultInstance() {
      return defaultInstance;
    }
    
    public Operation getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.bigfast.protobuf.OffHeapCacheProtoBuf.internal_static_com_bigfast_protobuf_Operation_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.bigfast.protobuf.OffHeapCacheProtoBuf.internal_static_com_bigfast_protobuf_Operation_fieldAccessorTable;
    }
    
    // optional string putKey = 1;
    public static final int PUTKEY_FIELD_NUMBER = 1;
    private boolean hasPutKey;
    private java.lang.String putKey_ = "";
    public boolean hasPutKey() { return hasPutKey; }
    public java.lang.String getPutKey() { return putKey_; }
    
    // optional string putValue = 2;
    public static final int PUTVALUE_FIELD_NUMBER = 2;
    private boolean hasPutValue;
    private java.lang.String putValue_ = "";
    public boolean hasPutValue() { return hasPutValue; }
    public java.lang.String getPutValue() { return putValue_; }
    
    // optional string getKey = 3;
    public static final int GETKEY_FIELD_NUMBER = 3;
    private boolean hasGetKey;
    private java.lang.String getKey_ = "";
    public boolean hasGetKey() { return hasGetKey; }
    public java.lang.String getGetKey() { return getKey_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasPutKey()) {
        output.writeString(1, getPutKey());
      }
      if (hasPutValue()) {
        output.writeString(2, getPutValue());
      }
      if (hasGetKey()) {
        output.writeString(3, getGetKey());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasPutKey()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getPutKey());
      }
      if (hasPutValue()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getPutValue());
      }
      if (hasGetKey()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(3, getGetKey());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.bigfast.protobuf.OffHeapCacheProtoBuf.Operation parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.bigfast.protobuf.OffHeapCacheProtoBuf.Operation parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.bigfast.protobuf.OffHeapCacheProtoBuf.Operation parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.bigfast.protobuf.OffHeapCacheProtoBuf.Operation parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.bigfast.protobuf.OffHeapCacheProtoBuf.Operation parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.bigfast.protobuf.OffHeapCacheProtoBuf.Operation parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.bigfast.protobuf.OffHeapCacheProtoBuf.Operation parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.bigfast.protobuf.OffHeapCacheProtoBuf.Operation parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.bigfast.protobuf.OffHeapCacheProtoBuf.Operation parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.bigfast.protobuf.OffHeapCacheProtoBuf.Operation parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.bigfast.protobuf.OffHeapCacheProtoBuf.Operation prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.bigfast.protobuf.OffHeapCacheProtoBuf.Operation result;
      
      // Construct using com.bigfast.protobuf.OffHeapCacheProtoBuf.Operation.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.bigfast.protobuf.OffHeapCacheProtoBuf.Operation();
        return builder;
      }
      
      protected com.bigfast.protobuf.OffHeapCacheProtoBuf.Operation internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.bigfast.protobuf.OffHeapCacheProtoBuf.Operation();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.bigfast.protobuf.OffHeapCacheProtoBuf.Operation.getDescriptor();
      }
      
      public com.bigfast.protobuf.OffHeapCacheProtoBuf.Operation getDefaultInstanceForType() {
        return com.bigfast.protobuf.OffHeapCacheProtoBuf.Operation.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.bigfast.protobuf.OffHeapCacheProtoBuf.Operation build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.bigfast.protobuf.OffHeapCacheProtoBuf.Operation buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.bigfast.protobuf.OffHeapCacheProtoBuf.Operation buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.bigfast.protobuf.OffHeapCacheProtoBuf.Operation returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.bigfast.protobuf.OffHeapCacheProtoBuf.Operation) {
          return mergeFrom((com.bigfast.protobuf.OffHeapCacheProtoBuf.Operation)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.bigfast.protobuf.OffHeapCacheProtoBuf.Operation other) {
        if (other == com.bigfast.protobuf.OffHeapCacheProtoBuf.Operation.getDefaultInstance()) return this;
        if (other.hasPutKey()) {
          setPutKey(other.getPutKey());
        }
        if (other.hasPutValue()) {
          setPutValue(other.getPutValue());
        }
        if (other.hasGetKey()) {
          setGetKey(other.getGetKey());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              setPutKey(input.readString());
              break;
            }
            case 18: {
              setPutValue(input.readString());
              break;
            }
            case 26: {
              setGetKey(input.readString());
              break;
            }
          }
        }
      }
      
      
      // optional string putKey = 1;
      public boolean hasPutKey() {
        return result.hasPutKey();
      }
      public java.lang.String getPutKey() {
        return result.getPutKey();
      }
      public Builder setPutKey(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasPutKey = true;
        result.putKey_ = value;
        return this;
      }
      public Builder clearPutKey() {
        result.hasPutKey = false;
        result.putKey_ = getDefaultInstance().getPutKey();
        return this;
      }
      
      // optional string putValue = 2;
      public boolean hasPutValue() {
        return result.hasPutValue();
      }
      public java.lang.String getPutValue() {
        return result.getPutValue();
      }
      public Builder setPutValue(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasPutValue = true;
        result.putValue_ = value;
        return this;
      }
      public Builder clearPutValue() {
        result.hasPutValue = false;
        result.putValue_ = getDefaultInstance().getPutValue();
        return this;
      }
      
      // optional string getKey = 3;
      public boolean hasGetKey() {
        return result.hasGetKey();
      }
      public java.lang.String getGetKey() {
        return result.getGetKey();
      }
      public Builder setGetKey(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasGetKey = true;
        result.getKey_ = value;
        return this;
      }
      public Builder clearGetKey() {
        result.hasGetKey = false;
        result.getKey_ = getDefaultInstance().getGetKey();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.bigfast.protobuf.Operation)
    }
    
    static {
      defaultInstance = new Operation(true);
      com.bigfast.protobuf.OffHeapCacheProtoBuf.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.bigfast.protobuf.Operation)
  }
  
  public static final class Operations extends
      com.google.protobuf.GeneratedMessage {
    // Use Operations.newBuilder() to construct.
    private Operations() {
      initFields();
    }
    private Operations(boolean noInit) {}
    
    private static final Operations defaultInstance;
    public static Operations getDefaultInstance() {
      return defaultInstance;
    }
    
    public Operations getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.bigfast.protobuf.OffHeapCacheProtoBuf.internal_static_com_bigfast_protobuf_Operations_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.bigfast.protobuf.OffHeapCacheProtoBuf.internal_static_com_bigfast_protobuf_Operations_fieldAccessorTable;
    }
    
    // repeated .com.bigfast.protobuf.Operation operation = 1;
    public static final int OPERATION_FIELD_NUMBER = 1;
    private java.util.List<com.bigfast.protobuf.OffHeapCacheProtoBuf.Operation> operation_ =
      java.util.Collections.emptyList();
    public java.util.List<com.bigfast.protobuf.OffHeapCacheProtoBuf.Operation> getOperationList() {
      return operation_;
    }
    public int getOperationCount() { return operation_.size(); }
    public com.bigfast.protobuf.OffHeapCacheProtoBuf.Operation getOperation(int index) {
      return operation_.get(index);
    }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (com.bigfast.protobuf.OffHeapCacheProtoBuf.Operation element : getOperationList()) {
        output.writeMessage(1, element);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      for (com.bigfast.protobuf.OffHeapCacheProtoBuf.Operation element : getOperationList()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, element);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.bigfast.protobuf.OffHeapCacheProtoBuf.Operations parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.bigfast.protobuf.OffHeapCacheProtoBuf.Operations parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.bigfast.protobuf.OffHeapCacheProtoBuf.Operations parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.bigfast.protobuf.OffHeapCacheProtoBuf.Operations parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.bigfast.protobuf.OffHeapCacheProtoBuf.Operations parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.bigfast.protobuf.OffHeapCacheProtoBuf.Operations parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.bigfast.protobuf.OffHeapCacheProtoBuf.Operations parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.bigfast.protobuf.OffHeapCacheProtoBuf.Operations parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.bigfast.protobuf.OffHeapCacheProtoBuf.Operations parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.bigfast.protobuf.OffHeapCacheProtoBuf.Operations parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.bigfast.protobuf.OffHeapCacheProtoBuf.Operations prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.bigfast.protobuf.OffHeapCacheProtoBuf.Operations result;
      
      // Construct using com.bigfast.protobuf.OffHeapCacheProtoBuf.Operations.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.bigfast.protobuf.OffHeapCacheProtoBuf.Operations();
        return builder;
      }
      
      protected com.bigfast.protobuf.OffHeapCacheProtoBuf.Operations internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.bigfast.protobuf.OffHeapCacheProtoBuf.Operations();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.bigfast.protobuf.OffHeapCacheProtoBuf.Operations.getDescriptor();
      }
      
      public com.bigfast.protobuf.OffHeapCacheProtoBuf.Operations getDefaultInstanceForType() {
        return com.bigfast.protobuf.OffHeapCacheProtoBuf.Operations.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.bigfast.protobuf.OffHeapCacheProtoBuf.Operations build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.bigfast.protobuf.OffHeapCacheProtoBuf.Operations buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.bigfast.protobuf.OffHeapCacheProtoBuf.Operations buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        if (result.operation_ != java.util.Collections.EMPTY_LIST) {
          result.operation_ =
            java.util.Collections.unmodifiableList(result.operation_);
        }
        com.bigfast.protobuf.OffHeapCacheProtoBuf.Operations returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.bigfast.protobuf.OffHeapCacheProtoBuf.Operations) {
          return mergeFrom((com.bigfast.protobuf.OffHeapCacheProtoBuf.Operations)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.bigfast.protobuf.OffHeapCacheProtoBuf.Operations other) {
        if (other == com.bigfast.protobuf.OffHeapCacheProtoBuf.Operations.getDefaultInstance()) return this;
        if (!other.operation_.isEmpty()) {
          if (result.operation_.isEmpty()) {
            result.operation_ = new java.util.ArrayList<com.bigfast.protobuf.OffHeapCacheProtoBuf.Operation>();
          }
          result.operation_.addAll(other.operation_);
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              com.bigfast.protobuf.OffHeapCacheProtoBuf.Operation.Builder subBuilder = com.bigfast.protobuf.OffHeapCacheProtoBuf.Operation.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addOperation(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      
      // repeated .com.bigfast.protobuf.Operation operation = 1;
      public java.util.List<com.bigfast.protobuf.OffHeapCacheProtoBuf.Operation> getOperationList() {
        return java.util.Collections.unmodifiableList(result.operation_);
      }
      public int getOperationCount() {
        return result.getOperationCount();
      }
      public com.bigfast.protobuf.OffHeapCacheProtoBuf.Operation getOperation(int index) {
        return result.getOperation(index);
      }
      public Builder setOperation(int index, com.bigfast.protobuf.OffHeapCacheProtoBuf.Operation value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.operation_.set(index, value);
        return this;
      }
      public Builder setOperation(int index, com.bigfast.protobuf.OffHeapCacheProtoBuf.Operation.Builder builderForValue) {
        result.operation_.set(index, builderForValue.build());
        return this;
      }
      public Builder addOperation(com.bigfast.protobuf.OffHeapCacheProtoBuf.Operation value) {
        if (value == null) {
          throw new NullPointerException();
        }
        if (result.operation_.isEmpty()) {
          result.operation_ = new java.util.ArrayList<com.bigfast.protobuf.OffHeapCacheProtoBuf.Operation>();
        }
        result.operation_.add(value);
        return this;
      }
      public Builder addOperation(com.bigfast.protobuf.OffHeapCacheProtoBuf.Operation.Builder builderForValue) {
        if (result.operation_.isEmpty()) {
          result.operation_ = new java.util.ArrayList<com.bigfast.protobuf.OffHeapCacheProtoBuf.Operation>();
        }
        result.operation_.add(builderForValue.build());
        return this;
      }
      public Builder addAllOperation(
          java.lang.Iterable<? extends com.bigfast.protobuf.OffHeapCacheProtoBuf.Operation> values) {
        if (result.operation_.isEmpty()) {
          result.operation_ = new java.util.ArrayList<com.bigfast.protobuf.OffHeapCacheProtoBuf.Operation>();
        }
        super.addAll(values, result.operation_);
        return this;
      }
      public Builder clearOperation() {
        result.operation_ = java.util.Collections.emptyList();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.bigfast.protobuf.Operations)
    }
    
    static {
      defaultInstance = new Operations(true);
      com.bigfast.protobuf.OffHeapCacheProtoBuf.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.bigfast.protobuf.Operations)
  }
  
  public static final class Result extends
      com.google.protobuf.GeneratedMessage {
    // Use Result.newBuilder() to construct.
    private Result() {
      initFields();
    }
    private Result(boolean noInit) {}
    
    private static final Result defaultInstance;
    public static Result getDefaultInstance() {
      return defaultInstance;
    }
    
    public Result getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.bigfast.protobuf.OffHeapCacheProtoBuf.internal_static_com_bigfast_protobuf_Result_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.bigfast.protobuf.OffHeapCacheProtoBuf.internal_static_com_bigfast_protobuf_Result_fieldAccessorTable;
    }
    
    // optional string putResult = 1;
    public static final int PUTRESULT_FIELD_NUMBER = 1;
    private boolean hasPutResult;
    private java.lang.String putResult_ = "";
    public boolean hasPutResult() { return hasPutResult; }
    public java.lang.String getPutResult() { return putResult_; }
    
    // optional string getResult = 2;
    public static final int GETRESULT_FIELD_NUMBER = 2;
    private boolean hasGetResult;
    private java.lang.String getResult_ = "";
    public boolean hasGetResult() { return hasGetResult; }
    public java.lang.String getGetResult() { return getResult_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasPutResult()) {
        output.writeString(1, getPutResult());
      }
      if (hasGetResult()) {
        output.writeString(2, getGetResult());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasPutResult()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getPutResult());
      }
      if (hasGetResult()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getGetResult());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.bigfast.protobuf.OffHeapCacheProtoBuf.Result parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.bigfast.protobuf.OffHeapCacheProtoBuf.Result parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.bigfast.protobuf.OffHeapCacheProtoBuf.Result parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.bigfast.protobuf.OffHeapCacheProtoBuf.Result parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.bigfast.protobuf.OffHeapCacheProtoBuf.Result parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.bigfast.protobuf.OffHeapCacheProtoBuf.Result parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.bigfast.protobuf.OffHeapCacheProtoBuf.Result parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.bigfast.protobuf.OffHeapCacheProtoBuf.Result parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.bigfast.protobuf.OffHeapCacheProtoBuf.Result parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.bigfast.protobuf.OffHeapCacheProtoBuf.Result parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.bigfast.protobuf.OffHeapCacheProtoBuf.Result prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.bigfast.protobuf.OffHeapCacheProtoBuf.Result result;
      
      // Construct using com.bigfast.protobuf.OffHeapCacheProtoBuf.Result.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.bigfast.protobuf.OffHeapCacheProtoBuf.Result();
        return builder;
      }
      
      protected com.bigfast.protobuf.OffHeapCacheProtoBuf.Result internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.bigfast.protobuf.OffHeapCacheProtoBuf.Result();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.bigfast.protobuf.OffHeapCacheProtoBuf.Result.getDescriptor();
      }
      
      public com.bigfast.protobuf.OffHeapCacheProtoBuf.Result getDefaultInstanceForType() {
        return com.bigfast.protobuf.OffHeapCacheProtoBuf.Result.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.bigfast.protobuf.OffHeapCacheProtoBuf.Result build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.bigfast.protobuf.OffHeapCacheProtoBuf.Result buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.bigfast.protobuf.OffHeapCacheProtoBuf.Result buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.bigfast.protobuf.OffHeapCacheProtoBuf.Result returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.bigfast.protobuf.OffHeapCacheProtoBuf.Result) {
          return mergeFrom((com.bigfast.protobuf.OffHeapCacheProtoBuf.Result)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.bigfast.protobuf.OffHeapCacheProtoBuf.Result other) {
        if (other == com.bigfast.protobuf.OffHeapCacheProtoBuf.Result.getDefaultInstance()) return this;
        if (other.hasPutResult()) {
          setPutResult(other.getPutResult());
        }
        if (other.hasGetResult()) {
          setGetResult(other.getGetResult());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              setPutResult(input.readString());
              break;
            }
            case 18: {
              setGetResult(input.readString());
              break;
            }
          }
        }
      }
      
      
      // optional string putResult = 1;
      public boolean hasPutResult() {
        return result.hasPutResult();
      }
      public java.lang.String getPutResult() {
        return result.getPutResult();
      }
      public Builder setPutResult(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasPutResult = true;
        result.putResult_ = value;
        return this;
      }
      public Builder clearPutResult() {
        result.hasPutResult = false;
        result.putResult_ = getDefaultInstance().getPutResult();
        return this;
      }
      
      // optional string getResult = 2;
      public boolean hasGetResult() {
        return result.hasGetResult();
      }
      public java.lang.String getGetResult() {
        return result.getGetResult();
      }
      public Builder setGetResult(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasGetResult = true;
        result.getResult_ = value;
        return this;
      }
      public Builder clearGetResult() {
        result.hasGetResult = false;
        result.getResult_ = getDefaultInstance().getGetResult();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.bigfast.protobuf.Result)
    }
    
    static {
      defaultInstance = new Result(true);
      com.bigfast.protobuf.OffHeapCacheProtoBuf.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.bigfast.protobuf.Result)
  }
  
  public static final class Results extends
      com.google.protobuf.GeneratedMessage {
    // Use Results.newBuilder() to construct.
    private Results() {
      initFields();
    }
    private Results(boolean noInit) {}
    
    private static final Results defaultInstance;
    public static Results getDefaultInstance() {
      return defaultInstance;
    }
    
    public Results getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.bigfast.protobuf.OffHeapCacheProtoBuf.internal_static_com_bigfast_protobuf_Results_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.bigfast.protobuf.OffHeapCacheProtoBuf.internal_static_com_bigfast_protobuf_Results_fieldAccessorTable;
    }
    
    // repeated .com.bigfast.protobuf.Result result = 1;
    public static final int RESULT_FIELD_NUMBER = 1;
    private java.util.List<com.bigfast.protobuf.OffHeapCacheProtoBuf.Result> result_ =
      java.util.Collections.emptyList();
    public java.util.List<com.bigfast.protobuf.OffHeapCacheProtoBuf.Result> getResultList() {
      return result_;
    }
    public int getResultCount() { return result_.size(); }
    public com.bigfast.protobuf.OffHeapCacheProtoBuf.Result getResult(int index) {
      return result_.get(index);
    }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (com.bigfast.protobuf.OffHeapCacheProtoBuf.Result element : getResultList()) {
        output.writeMessage(1, element);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      for (com.bigfast.protobuf.OffHeapCacheProtoBuf.Result element : getResultList()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, element);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.bigfast.protobuf.OffHeapCacheProtoBuf.Results parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.bigfast.protobuf.OffHeapCacheProtoBuf.Results parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.bigfast.protobuf.OffHeapCacheProtoBuf.Results parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.bigfast.protobuf.OffHeapCacheProtoBuf.Results parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.bigfast.protobuf.OffHeapCacheProtoBuf.Results parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.bigfast.protobuf.OffHeapCacheProtoBuf.Results parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.bigfast.protobuf.OffHeapCacheProtoBuf.Results parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.bigfast.protobuf.OffHeapCacheProtoBuf.Results parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.bigfast.protobuf.OffHeapCacheProtoBuf.Results parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.bigfast.protobuf.OffHeapCacheProtoBuf.Results parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.bigfast.protobuf.OffHeapCacheProtoBuf.Results prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.bigfast.protobuf.OffHeapCacheProtoBuf.Results result;
      
      // Construct using com.bigfast.protobuf.OffHeapCacheProtoBuf.Results.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.bigfast.protobuf.OffHeapCacheProtoBuf.Results();
        return builder;
      }
      
      protected com.bigfast.protobuf.OffHeapCacheProtoBuf.Results internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.bigfast.protobuf.OffHeapCacheProtoBuf.Results();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.bigfast.protobuf.OffHeapCacheProtoBuf.Results.getDescriptor();
      }
      
      public com.bigfast.protobuf.OffHeapCacheProtoBuf.Results getDefaultInstanceForType() {
        return com.bigfast.protobuf.OffHeapCacheProtoBuf.Results.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.bigfast.protobuf.OffHeapCacheProtoBuf.Results build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.bigfast.protobuf.OffHeapCacheProtoBuf.Results buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.bigfast.protobuf.OffHeapCacheProtoBuf.Results buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        if (result.result_ != java.util.Collections.EMPTY_LIST) {
          result.result_ =
            java.util.Collections.unmodifiableList(result.result_);
        }
        com.bigfast.protobuf.OffHeapCacheProtoBuf.Results returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.bigfast.protobuf.OffHeapCacheProtoBuf.Results) {
          return mergeFrom((com.bigfast.protobuf.OffHeapCacheProtoBuf.Results)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.bigfast.protobuf.OffHeapCacheProtoBuf.Results other) {
        if (other == com.bigfast.protobuf.OffHeapCacheProtoBuf.Results.getDefaultInstance()) return this;
        if (!other.result_.isEmpty()) {
          if (result.result_.isEmpty()) {
            result.result_ = new java.util.ArrayList<com.bigfast.protobuf.OffHeapCacheProtoBuf.Result>();
          }
          result.result_.addAll(other.result_);
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              com.bigfast.protobuf.OffHeapCacheProtoBuf.Result.Builder subBuilder = com.bigfast.protobuf.OffHeapCacheProtoBuf.Result.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addResult(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      
      // repeated .com.bigfast.protobuf.Result result = 1;
      public java.util.List<com.bigfast.protobuf.OffHeapCacheProtoBuf.Result> getResultList() {
        return java.util.Collections.unmodifiableList(result.result_);
      }
      public int getResultCount() {
        return result.getResultCount();
      }
      public com.bigfast.protobuf.OffHeapCacheProtoBuf.Result getResult(int index) {
        return result.getResult(index);
      }
      public Builder setResult(int index, com.bigfast.protobuf.OffHeapCacheProtoBuf.Result value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.result_.set(index, value);
        return this;
      }
      public Builder setResult(int index, com.bigfast.protobuf.OffHeapCacheProtoBuf.Result.Builder builderForValue) {
        result.result_.set(index, builderForValue.build());
        return this;
      }
      public Builder addResult(com.bigfast.protobuf.OffHeapCacheProtoBuf.Result value) {
        if (value == null) {
          throw new NullPointerException();
        }
        if (result.result_.isEmpty()) {
          result.result_ = new java.util.ArrayList<com.bigfast.protobuf.OffHeapCacheProtoBuf.Result>();
        }
        result.result_.add(value);
        return this;
      }
      public Builder addResult(com.bigfast.protobuf.OffHeapCacheProtoBuf.Result.Builder builderForValue) {
        if (result.result_.isEmpty()) {
          result.result_ = new java.util.ArrayList<com.bigfast.protobuf.OffHeapCacheProtoBuf.Result>();
        }
        result.result_.add(builderForValue.build());
        return this;
      }
      public Builder addAllResult(
          java.lang.Iterable<? extends com.bigfast.protobuf.OffHeapCacheProtoBuf.Result> values) {
        if (result.result_.isEmpty()) {
          result.result_ = new java.util.ArrayList<com.bigfast.protobuf.OffHeapCacheProtoBuf.Result>();
        }
        super.addAll(values, result.result_);
        return this;
      }
      public Builder clearResult() {
        result.result_ = java.util.Collections.emptyList();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.bigfast.protobuf.Results)
    }
    
    static {
      defaultInstance = new Results(true);
      com.bigfast.protobuf.OffHeapCacheProtoBuf.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.bigfast.protobuf.Results)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_bigfast_protobuf_Operation_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_bigfast_protobuf_Operation_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_bigfast_protobuf_Operations_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_bigfast_protobuf_Operations_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_bigfast_protobuf_Result_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_bigfast_protobuf_Result_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_bigfast_protobuf_Results_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_bigfast_protobuf_Results_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032OffHeapCacheProtoBuf.proto\022\024com.bigfas" +
      "t.protobuf\"=\n\tOperation\022\016\n\006putKey\030\001 \001(\t\022" +
      "\020\n\010putValue\030\002 \001(\t\022\016\n\006getKey\030\003 \001(\t\"@\n\nOpe" +
      "rations\0222\n\toperation\030\001 \003(\0132\037.com.bigfast" +
      ".protobuf.Operation\".\n\006Result\022\021\n\tputResu" +
      "lt\030\001 \001(\t\022\021\n\tgetResult\030\002 \001(\t\"7\n\007Results\022," +
      "\n\006result\030\001 \003(\0132\034.com.bigfast.protobuf.Re" +
      "sultB\002H\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_bigfast_protobuf_Operation_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_bigfast_protobuf_Operation_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_bigfast_protobuf_Operation_descriptor,
              new java.lang.String[] { "PutKey", "PutValue", "GetKey", },
              com.bigfast.protobuf.OffHeapCacheProtoBuf.Operation.class,
              com.bigfast.protobuf.OffHeapCacheProtoBuf.Operation.Builder.class);
          internal_static_com_bigfast_protobuf_Operations_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_bigfast_protobuf_Operations_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_bigfast_protobuf_Operations_descriptor,
              new java.lang.String[] { "Operation", },
              com.bigfast.protobuf.OffHeapCacheProtoBuf.Operations.class,
              com.bigfast.protobuf.OffHeapCacheProtoBuf.Operations.Builder.class);
          internal_static_com_bigfast_protobuf_Result_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_com_bigfast_protobuf_Result_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_bigfast_protobuf_Result_descriptor,
              new java.lang.String[] { "PutResult", "GetResult", },
              com.bigfast.protobuf.OffHeapCacheProtoBuf.Result.class,
              com.bigfast.protobuf.OffHeapCacheProtoBuf.Result.Builder.class);
          internal_static_com_bigfast_protobuf_Results_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_com_bigfast_protobuf_Results_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_bigfast_protobuf_Results_descriptor,
              new java.lang.String[] { "Result", },
              com.bigfast.protobuf.OffHeapCacheProtoBuf.Results.class,
              com.bigfast.protobuf.OffHeapCacheProtoBuf.Results.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
